import { BiShieldQuarter } from "react-icons/bi";
import { FaRegClock } from "react-icons/fa";
import { FiUserCheck } from "react-icons/fi";
import { IoMdCheckmarkCircleOutline } from "react-icons/io";
import { LuCrown, LuUsers } from "react-icons/lu";

export const submissions = [
  {
    id: "sub_001",
    name: "John Doe",
    test: "Frontend Developer Assessment",
    score: "85%",
    status: "graded",
    date: "2024-01-15",
    time: "14:30",
  },
  {
    id: "sub_002",
    name: "Sarah Wilson",
    test: "Data Analyst Test",
    score: "92%",
    status: "graded",
    date: "2024-01-15",
    time: "13:45",
  },
  {
    id: "sub_003",
    name: "Mike Johnson",
    test: "Backend Developer Test",
    score: "-",
    status: "pending",
    date: "2024-01-15",
    time: "12:20",
  },
  {
    id: "sub_004",
    name: "Emily Chen",
    test: "UI/UX Designer Assessment",
    score: "78%",
    status: "graded",
    date: "2024-01-14",
    time: "16:15",
  },
  {
    id: "sub_005",
    name: "David Rodriguez",
    test: "Full Stack Developer Test",
    score: "88%",
    status: "graded",
    date: "2024-01-14",
    time: "15:30",
  },
  {
    id: "sub_006",
    name: "Lisa Thompson",
    test: "Marketing Specialist Assessment",
    score: "91%",
    status: "graded",
    date: "2024-01-14",
    time: "11:45",
  },
  {
    id: "sub_007",
    name: "James Park",
    test: "DevOps Engineer Test",
    score: "-",
    status: "pending",
    date: "2024-01-14",
    time: "10:20",
  },
  {
    id: "sub_008",
    name: "Amanda Foster",
    test: "Product Manager Assessment",
    score: "89%",
    status: "graded",
    date: "2024-01-13",
    time: "16:40",
  },
  {
    id: "sub_009",
    name: "Robert Kim",
    test: "Mobile Developer Test",
    score: "76%",
    status: "graded",
    date: "2024-01-13",
    time: "14:15",
  },
  {
    id: "sub_010",
    name: "Maria Garcia",
    test: "Content Writer Assessment",
    score: "94%",
    status: "graded",
    date: "2024-01-13",
    time: "13:30",
  },
  {
    id: "sub_011",
    name: "Kevin Wong",
    test: "QA Engineer Test",
    score: "82%",
    status: "graded",
    date: "2024-01-13",
    time: "12:10",
  },
  {
    id: "sub_012",
    name: "Jennifer Adams",
    test: "Graphic Designer Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-13",
    time: "11:25",
  },
  {
    id: "sub_013",
    name: "Chris Martinez",
    test: "Data Scientist Test",
    score: "96%",
    status: "graded",
    date: "2024-01-12",
    time: "15:45",
  },
  {
    id: "sub_014",
    name: "Nicole Brown",
    test: "Business Analyst Assessment",
    score: "87%",
    status: "graded",
    date: "2024-01-12",
    time: "14:20",
  },
  {
    id: "sub_015",
    name: "Steven Taylor",
    test: "Security Engineer Test",
    score: "83%",
    status: "graded",
    date: "2024-01-12",
    time: "13:55",
  },
  {
    id: "sub_016",
    name: "Rachel Green",
    test: "Project Manager Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-12",
    time: "12:30",
  },
  {
    id: "sub_017",
    name: "Daniel Lee",
    test: "Cloud Engineer Test",
    score: "90%",
    status: "graded",
    date: "2024-01-11",
    time: "16:10",
  },
  {
    id: "sub_018",
    name: "Ashley Davis",
    test: "Social Media Manager Assessment",
    score: "88%",
    status: "graded",
    date: "2024-01-11",
    time: "15:25",
  },
  {
    id: "sub_019",
    name: "Michael Turner",
    test: "Sales Representative Test",
    score: "79%",
    status: "graded",
    date: "2024-01-11",
    time: "14:40",
  },
  {
    id: "sub_020",
    name: "Jessica White",
    test: "HR Specialist Assessment",
    score: "93%",
    status: "graded",
    date: "2024-01-11",
    time: "13:15",
  },
  {
    id: "sub_021",
    name: "Brian Miller",
    test: "Database Administrator Test",
    score: "-",
    status: "pending",
    date: "2024-01-11",
    time: "12:05",
  },
  {
    id: "sub_022",
    name: "Stephanie Clark",
    test: "Finance Analyst Assessment",
    score: "86%",
    status: "graded",
    date: "2024-01-10",
    time: "16:30",
  },
  {
    id: "sub_023",
    name: "Anthony Lewis",
    test: "Software Architect Test",
    score: "95%",
    status: "graded",
    date: "2024-01-10",
    time: "15:10",
  },
  {
    id: "sub_024",
    name: "Melissa Hall",
    test: "Customer Success Manager Assessment",
    score: "84%",
    status: "graded",
    date: "2024-01-10",
    time: "14:35",
  },
  {
    id: "sub_025",
    name: "Ryan Walker",
    test: "Network Engineer Test",
    score: "81%",
    status: "graded",
    date: "2024-01-10",
    time: "13:50",
  },
  {
    id: "sub_026",
    name: "Laura Young",
    test: "Digital Marketing Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-10",
    time: "12:15",
  },
  {
    id: "sub_027",
    name: "Jason Scott",
    test: "Technical Writer Test",
    score: "89%",
    status: "graded",
    date: "2024-01-09",
    time: "16:20",
  },
  {
    id: "sub_028",
    name: "Kimberly King",
    test: "Operations Manager Assessment",
    score: "87%",
    status: "graded",
    date: "2024-01-09",
    time: "15:40",
  },
  {
    id: "sub_029",
    name: "Thomas Wright",
    test: "Machine Learning Engineer Test",
    score: "92%",
    status: "graded",
    date: "2024-01-09",
    time: "14:25",
  },
  {
    id: "sub_030",
    name: "Karen Lopez",
    test: "Legal Counsel Assessment",
    score: "90%",
    status: "graded",
    date: "2024-01-09",
    time: "13:10",
  },
];

export const viewSubmissionData = [
  {
    id: "sub_001",
    name: "John Doe",
    test: { name: "Frontend Developer", category: "Technical" },
    score: "85%",
    status: "graded",
    date: "2024-01-15",
    time: "14:30",
    flag: "clean",
    progress: { totalQuestions: 20, attemptedQuestions: 20 },
  },
  {
    id: "sub_002",
    name: "Sarah Wilson",
    test: { name: "Data Analyst Test", category: "Analytical" },
    score: "92%",
    status: "graded",
    date: "2024-01-15",
    time: "13:45",
    flag: "clean",
    progress: { totalQuestions: 25, attemptedQuestions: 25 },
  },
  {
    id: "sub_003",
    name: "Mike Johnson",
    test: { name: "Backend Developer Test", category: "Technical" },
    score: "-",
    status: "pending",
    date: "2024-01-15",
    time: "12:20",
    flag: "suspicious",
    progress: { totalQuestions: 30, attemptedQuestions: 12 },
  },
  {
    id: "sub_004",
    name: "Emily Carter",
    test: { name: "Marketing Strategy", category: "Business" },
    score: "78%",
    status: "graded",
    date: "2024-01-15",
    time: "15:10",
    flag: "clean",
    progress: { totalQuestions: 15, attemptedQuestions: 15 },
  },
  {
    id: "sub_005",
    name: "David Lee",
    test: { name: "Machine Learning", category: "Technical" },
    score: "66%",
    status: "graded",
    date: "2024-01-15",
    time: "16:45",
    flag: "review",
    progress: { totalQuestions: 40, attemptedQuestions: 36 },
  },
  {
    id: "sub_006",
    name: "Ayesha Khan",
    test: { name: "Product Design", category: "Design" },
    score: "88%",
    status: "graded",
    date: "2024-01-16",
    time: "11:00",
    flag: "clean",
    progress: { totalQuestions: 18, attemptedQuestions: 18 },
  },
  {
    id: "sub_007",
    name: "Tom Baker",
    test: { name: "JavaScript Fundamentals", category: "Technical" },
    score: "91%",
    status: "graded",
    date: "2024-01-16",
    time: "11:30",
    flag: "clean",
    progress: { totalQuestions: 20, attemptedQuestions: 20 },
  },
  {
    id: "sub_008",
    name: "Natalie Smith",
    test: { name: "HR Situational", category: "HR" },
    score: "73%",
    status: "graded",
    date: "2024-01-16",
    time: "13:15",
    flag: "suspicious",
    progress: { totalQuestions: 10, attemptedQuestions: 7 },
  },
  {
    id: "sub_009",
    name: "Mohammed Ali",
    test: { name: "Linux System Admin", category: "Technical" },
    score: "-",
    status: "pending",
    date: "2024-01-16",
    time: "14:10",
    flag: "network-issue",
    progress: { totalQuestions: 35, attemptedQuestions: 10 },
  },
  {
    id: "sub_010",
    name: "Grace Lin",
    test: { name: "Content Writing", category: "Creative" },
    score: "82%",
    status: "graded",
    date: "2024-01-16",
    time: "15:40",
    flag: "clean",
    progress: { totalQuestions: 12, attemptedQuestions: 12 },
  },
];

export const userManagementStats = [
  {
    key: "totalAdmins",
    label: "Total Admins",
    growthColor: "text-green-600",
    color: "blue",
    rightIcon: <LuCrown className="text-xl" />,
  },
  {
    key: "totalHRs",
    label: "HR",
    growthColor: "text-green-600",
    color: "green",
    rightIcon: <BiShieldQuarter className="text-xl" />,
  },
  {
    key: "totalActiveUsers",
    label: "Active Users",
    growthColor: "text-orange-600",
    color: "green",
    rightIcon: <FiUserCheck className="text-xl" />,
  },
  {
    key: "totalCandidates",
    label: "Candidates",
    growthColor: "text-orange-600",
    color: "orange",
    rightIcon: <LuUsers className="text-xl" />,
  },
];

export const categoryOptions = [
  { value: "", label: "Select category" },
  { value: "programming", label: "Programming" },
  { value: "design", label: "Design" },
  { value: "marketing", label: "Marketing" },
  { value: "general", label: "General Knowledge" },
];

export const roleOptions = [
  { label: "All Roles", value: "all" },
  { label: "Admin", value: "admin" },
  { label: "HR", value: "hr" },
  { label: "Candidate", value: "candidate" },
];

export const statusOptions = [
  { label: "All Status", value: "all" },
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
];

export const roleOptionsModal = [
  { label: "Select Role", value: "" },
  { label: "Admin", value: "admin" },
  { label: "HR", value: "hr" },
  { label: "Candidate", value: "candidate" },
];

export const approvedRoles = [
  { label: "Candidate", value: "CANDIDATE" },
  { label: "HR", value: "HR" },
];
