import { BiShieldQuarter } from "react-icons/bi";
import { FaRegClock } from "react-icons/fa";
import { FiUserCheck } from "react-icons/fi";
import { IoMdCheckmarkCircleOutline } from "react-icons/io";
import { LuCrown, LuUsers } from "react-icons/lu";

export const submissions = [
  {
    id: "sub_001",
    name: "John Doe",
    test: "Frontend Developer Assessment",
    score: "85%",
    status: "graded",
    date: "2024-01-15",
    time: "14:30",
  },
  {
    id: "sub_002",
    name: "Sarah Wilson",
    test: "Data Analyst Test",
    score: "92%",
    status: "graded",
    date: "2024-01-15",
    time: "13:45",
  },
  {
    id: "sub_003",
    name: "Mike Johnson",
    test: "Backend Developer Test",
    score: "-",
    status: "pending",
    date: "2024-01-15",
    time: "12:20",
  },
  {
    id: "sub_004",
    name: "Emily Chen",
    test: "UI/UX Designer Assessment",
    score: "78%",
    status: "graded",
    date: "2024-01-14",
    time: "16:15",
  },
  {
    id: "sub_005",
    name: "David Rodriguez",
    test: "Full Stack Developer Test",
    score: "88%",
    status: "graded",
    date: "2024-01-14",
    time: "15:30",
  },
  {
    id: "sub_006",
    name: "Lisa Thompson",
    test: "Marketing Specialist Assessment",
    score: "91%",
    status: "graded",
    date: "2024-01-14",
    time: "11:45",
  },
  {
    id: "sub_007",
    name: "James Park",
    test: "DevOps Engineer Test",
    score: "-",
    status: "pending",
    date: "2024-01-14",
    time: "10:20",
  },
  {
    id: "sub_008",
    name: "Amanda Foster",
    test: "Product Manager Assessment",
    score: "89%",
    status: "graded",
    date: "2024-01-13",
    time: "16:40",
  },
  {
    id: "sub_009",
    name: "Robert Kim",
    test: "Mobile Developer Test",
    score: "76%",
    status: "graded",
    date: "2024-01-13",
    time: "14:15",
  },
  {
    id: "sub_010",
    name: "Maria Garcia",
    test: "Content Writer Assessment",
    score: "94%",
    status: "graded",
    date: "2024-01-13",
    time: "13:30",
  },
  {
    id: "sub_011",
    name: "Kevin Wong",
    test: "QA Engineer Test",
    score: "82%",
    status: "graded",
    date: "2024-01-13",
    time: "12:10",
  },
  {
    id: "sub_012",
    name: "Jennifer Adams",
    test: "Graphic Designer Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-13",
    time: "11:25",
  },
  {
    id: "sub_013",
    name: "Chris Martinez",
    test: "Data Scientist Test",
    score: "96%",
    status: "graded",
    date: "2024-01-12",
    time: "15:45",
  },
  {
    id: "sub_014",
    name: "Nicole Brown",
    test: "Business Analyst Assessment",
    score: "87%",
    status: "graded",
    date: "2024-01-12",
    time: "14:20",
  },
  {
    id: "sub_015",
    name: "Steven Taylor",
    test: "Security Engineer Test",
    score: "83%",
    status: "graded",
    date: "2024-01-12",
    time: "13:55",
  },
  {
    id: "sub_016",
    name: "Rachel Green",
    test: "Project Manager Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-12",
    time: "12:30",
  },
  {
    id: "sub_017",
    name: "Daniel Lee",
    test: "Cloud Engineer Test",
    score: "90%",
    status: "graded",
    date: "2024-01-11",
    time: "16:10",
  },
  {
    id: "sub_018",
    name: "Ashley Davis",
    test: "Social Media Manager Assessment",
    score: "88%",
    status: "graded",
    date: "2024-01-11",
    time: "15:25",
  },
  {
    id: "sub_019",
    name: "Michael Turner",
    test: "Sales Representative Test",
    score: "79%",
    status: "graded",
    date: "2024-01-11",
    time: "14:40",
  },
  {
    id: "sub_020",
    name: "Jessica White",
    test: "HR Specialist Assessment",
    score: "93%",
    status: "graded",
    date: "2024-01-11",
    time: "13:15",
  },
  {
    id: "sub_021",
    name: "Brian Miller",
    test: "Database Administrator Test",
    score: "-",
    status: "pending",
    date: "2024-01-11",
    time: "12:05",
  },
  {
    id: "sub_022",
    name: "Stephanie Clark",
    test: "Finance Analyst Assessment",
    score: "86%",
    status: "graded",
    date: "2024-01-10",
    time: "16:30",
  },
  {
    id: "sub_023",
    name: "Anthony Lewis",
    test: "Software Architect Test",
    score: "95%",
    status: "graded",
    date: "2024-01-10",
    time: "15:10",
  },
  {
    id: "sub_024",
    name: "Melissa Hall",
    test: "Customer Success Manager Assessment",
    score: "84%",
    status: "graded",
    date: "2024-01-10",
    time: "14:35",
  },
  {
    id: "sub_025",
    name: "Ryan Walker",
    test: "Network Engineer Test",
    score: "81%",
    status: "graded",
    date: "2024-01-10",
    time: "13:50",
  },
  {
    id: "sub_026",
    name: "Laura Young",
    test: "Digital Marketing Assessment",
    score: "-",
    status: "pending",
    date: "2024-01-10",
    time: "12:15",
  },
  {
    id: "sub_027",
    name: "Jason Scott",
    test: "Technical Writer Test",
    score: "89%",
    status: "graded",
    date: "2024-01-09",
    time: "16:20",
  },
  {
    id: "sub_028",
    name: "Kimberly King",
    test: "Operations Manager Assessment",
    score: "87%",
    status: "graded",
    date: "2024-01-09",
    time: "15:40",
  },
  {
    id: "sub_029",
    name: "Thomas Wright",
    test: "Machine Learning Engineer Test",
    score: "92%",
    status: "graded",
    date: "2024-01-09",
    time: "14:25",
  },
  {
    id: "sub_030",
    name: "Karen Lopez",
    test: "Legal Counsel Assessment",
    score: "90%",
    status: "graded",
    date: "2024-01-09",
    time: "13:10",
  }
];

export const viewSubmissionData = [
  {
    id: "sub_001",
    name: "John Doe",
    test: { name: "Frontend Developer", category: "Technical" },
    score: "85%",
    status: "graded",
    date: "2024-01-15",
    time: "14:30",
    flag: "clean",
    progress: { totalQuestions: 20, attemptedQuestions: 20 },
  },
  {
    id: "sub_002",
    name: "Sarah Wilson",
    test: { name: "Data Analyst Test", category: "Analytical" },
    score: "92%",
    status: "graded",
    date: "2024-01-15",
    time: "13:45",
    flag: "clean",
    progress: { totalQuestions: 25, attemptedQuestions: 25 },
  },
  {
    id: "sub_003",
    name: "Mike Johnson",
    test: { name: "Backend Developer Test", category: "Technical" },
    score: "-",
    status: "pending",
    date: "2024-01-15",
    time: "12:20",
    flag: "suspicious",
    progress: { totalQuestions: 30, attemptedQuestions: 12 },
  },
  {
    id: "sub_004",
    name: "Emily Carter",
    test: { name: "Marketing Strategy", category: "Business" },
    score: "78%",
    status: "graded",
    date: "2024-01-15",
    time: "15:10",
    flag: "clean",
    progress: { totalQuestions: 15, attemptedQuestions: 15 },
  },
  {
    id: "sub_005",
    name: "David Lee",
    test: { name: "Machine Learning", category: "Technical" },
    score: "66%",
    status: "graded",
    date: "2024-01-15",
    time: "16:45",
    flag: "review",
    progress: { totalQuestions: 40, attemptedQuestions: 36 },
  },
  {
    id: "sub_006",
    name: "Ayesha Khan",
    test: { name: "Product Design", category: "Design" },
    score: "88%",
    status: "graded",
    date: "2024-01-16",
    time: "11:00",
    flag: "clean",
    progress: { totalQuestions: 18, attemptedQuestions: 18 },
  },
  {
    id: "sub_007",
    name: "Tom Baker",
    test: { name: "JavaScript Fundamentals", category: "Technical" },
    score: "91%",
    status: "graded",
    date: "2024-01-16",
    time: "11:30",
    flag: "clean",
    progress: { totalQuestions: 20, attemptedQuestions: 20 },
  },
  {
    id: "sub_008",
    name: "Natalie Smith",
    test: { name: "HR Situational", category: "HR" },
    score: "73%",
    status: "graded",
    date: "2024-01-16",
    time: "13:15",
    flag: "suspicious",
    progress: { totalQuestions: 10, attemptedQuestions: 7 },
  },
  {
    id: "sub_009",
    name: "Mohammed Ali",
    test: { name: "Linux System Admin", category: "Technical" },
    score: "-",
    status: "pending",
    date: "2024-01-16",
    time: "14:10",
    flag: "network-issue",
    progress: { totalQuestions: 35, attemptedQuestions: 10 },
  },
  {
    id: "sub_010",
    name: "Grace Lin",
    test: { name: "Content Writing", category: "Creative" },
    score: "82%",
    status: "graded",
    date: "2024-01-16",
    time: "15:40",
    flag: "clean",
    progress: { totalQuestions: 12, attemptedQuestions: 12 },
  },
];


export const sampleQuestions = [
  {
    id: 1,
    type: "MCQ",
    marks: 2,
    awardedMarks: 2,
    question: "What is the primary purpose of React hooks?",
    candidateAnswer: "To manage state and lifecycle in functional components",
    correctAnswer: "To manage state and lifecycle in functional components",
    aiRemarks: "Correct understanding of React hooks concept.",
  },
  {
    id: 2,
    type: "TRUE_FALSE",
    marks: 1,
    awardedMarks: 1,
    question: "JavaScript is a statically typed programming language.",
    candidateAnswer: "False",
    correctAnswer: "False",
    aiRemarks: "Correct, JavaScript is dynamically typed.",
  },
  {
    id: 3,
    type: "DESCRIPTIVE",
    marks: 5,
    awardedMarks: 5,
    question: "Explain the concept of closures in JavaScript.",
    candidateAnswer: "Closures are functions that retain access to their lexical scope, even when the function is executed outside that scope.",
    correctAnswer: "Closures are functions that retain access to their lexical scope, even when the function is executed outside that scope.",
    aiRemarks: "Excellent explanation of closures.",
  }
];


export const userManagementStats = [
  {
    label: "Total Admins",
    value: "24",
    growthColor: "text-green-600",
    color: "blue",
    rightIcon: <LuCrown className="text-xl" />,
  },
  {
    label: "HR",
    value: "156",
    growthColor: "text-green-600",
    color: "green",
    rightIcon: <BiShieldQuarter className="text-xl" />,
  },
  {
    label: "Active Users",
    value: "8",
    growthColor: "text-orange-600",
    color: "green",
    rightIcon: <FiUserCheck className="text-xl" />,
  },
  {
    label: "Candidates",
    value: "8",
    growthColor: "text-orange-600",
    color: "orange",
    rightIcon: <LuUsers className="text-xl" />,
  },
];

export const usersData = [
  {
    id: "user_001",
    name: "John Admin",
    email: "john.admin@company.com",
    role: "Admin",
    status: "Active",
    testsCreated: 12,
    testsManaged: 45,
    lastActive: {date: "1/15/2024", time: "9:30:00 AM"},
  },
  {
    id: "user_002",
    name: "Sarah HR Manager",
    email: "sarah.hr@company.com",
    role: "HR",
    status: "Active",
    testsCreated: 8,
    testsManaged: 23,
    lastActive: {date: "1/15/2024", time: "8:45:00 AM"},
  },
  {
    id: "user_003",
    name: "Mike HR Specialist",
    email: "mike.hr@company.com",
    role: "HR",
    status: "Inactive",
    testsCreated: 3,
    testsManaged: 12,
    lastActive: {date: "1/10/2024", time: "4:20:00 PM"},
  },
  {
    id: "user_004",
    name: "Ayesha Khan",
    email: "ayesha.khan@candidates.com",
    role: "Candidate",
    status: "Active",
    testsAttempted: 2,
    lastActive: {date: "1/18/2024", time: "2:10:00 PM"},
  },
  {
    id: "user_005",
    name: "Daniel Smith",
    email: "daniel.smith@candidates.com",
    role: "Candidate",
    status: "Inactive",
    testsAttempted: 1,
    lastActive: {date: "1/12/2024", time: "11:00:00 AM"},
  },
  {
    id: "user_006",
    name: "Fatima Noor",
    email: "fatima.noor@company.com",
    role: "HR",
    status: "Active",
    testsCreated: 5,
    testsManaged: 15,
    lastActive: {date: "1/14/2024", time: "3:00:00 PM"},
  },
  {
    id: "user_007",
    name: "Ali Raza",
    email: "ali.raza@candidates.com",
    role: "Candidate",
    status: "Active",
    testsAttempted: 4,
    lastActive: {date: "1/16/2024", time: "10:00:00 AM"},
  },
  {
    id: "user_008",
    name: "Nida Hashmi",
    email: "nida.hashmi@company.com",
    role: "Admin",
    status: "Inactive",
    testsCreated: 7,
    testsManaged: 20,
    lastActive: {date: "1/13/2024", time: "5:45:00 PM"},
  }
];
